language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - chomod +x gradlew
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradelw clean build"

# CI 실행 완료 시 메일로 알람
# 확인
notifications:
  email:
    recipients:
      - hwanguebest@naver.com

