spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 61424815404-dv0dagnidtjtn7g6ptiafliaq9o6vhoi.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email

          naver:
            client-id: rVZhdRTG3KPaHf4YzH0_
            client-secret: p8jFctEY_g
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver

        provider:
          naver:
            authorization-uri: 'https://nid.naver.com/oauth2.0/authorize'
            token-uri: 'https://nid.naver.com/oauth2.0/token'
            user-info-uri: 'https://openapi.naver.com/v1/nid/me'
            user-name-attribute: 'response'